// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtdajmhznixlwntyiiun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0ZGFqbWh6bml4bHdudHlpaXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTk3MDYsImV4cCI6MjA3Mzk3NTcwNn0.fVYsklYo0swyHlQ15KxDEbiaM-Lq7Kazu7gpzK-UjEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});